#---
#- name: Deploy Tomcat using Ansible Role
#  hosts: web
#  become: yes
 # roles:
 #   - role: tomcat-Role/tomcat
  #    tomcat_group: "tomcat"
   #   tomcat_user: "tomcat"
---
- name: Deploy Tomcat using Ansible Role
  hosts: web
  become: yes
  roles:
    - role: tomcat-Role/tomcat
      tomcat_group: "tomcat"
      tomcat_user: "tomcat"

  tasks: 
    - name: Debug hosts
      debug:
        var: ansible_host
